# Generated by Django 4.1 on 2022-08-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
